version: '3.7'
services:
  db:
    container_name: exchange-rate-db
    image: postgres:latest
    restart: always
    environment:
      - TZ=UTC
      - POSTGRES_DATABASES=exchange_rate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6543:5432
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
    networks:
      - exchange_rate

  db_migrations:
    image: migrate/migrate
    container_name: db_migrations
    networks:
      - exchange_rate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    command: -path=/migrations -database postgres://postgres:postgres@db:5432/exchange_rate?sslmode=disable up

networks:
  exchange_rate:
    name: exchange_rate_network
    driver: bridge